Feature authentication
OleksiyNosov/NullPointerException pull request #4
Opened 2017-12-04 08:43 UTC by OleksiyNosov

2017-12-04 15:59 UTC, kohigh requested changes

2017-12-04 15:59 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +  def authenticate_with_password
Из-за твоей логической разбивки я сначала подумал, что ты 2 схемы аутентификации захотел сделать.

на самом деле 1 хук аутентификации должен быть.

authenticate_with_password должен быть частью воркфлоу sessions#create, а не бефор хуком.

2017-12-04 15:59 UTC, donasktello commented on app/controllers/application_controller.rb
> +  def resource_class
Вся вот эта resource_абстракция уже нормально загрузила контроллер, я бы это декомпозировал в какой-то модуль, типа resourceable, чтобы вся ресурс_контекстная движуха делегирована была, а не размывала контроллер.

2017-12-04 15:59 UTC, donasktello commented on spec/controllers/api/answers_controller_spec.rb
> +  describe 'GET #index' do
тесты пока проверять не буду, тебе пока есть, что переделать.

2017-12-04 15:59 UTC, donasktello commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 20171128155047) do
спрячь схему в гитигнор и удали из паблика.

2017-12-04 15:59 UTC, donasktello commented on db/migrate/20171128144653_create_users.rb
> +      t.string :email
почему бы тут индекс не добавить?

2017-12-04 15:59 UTC, donasktello commented on config/routes.rb
> +    resource :profile, only: %i[show create update]
как раз-таки наоборот.

у тебя ресурс какой в профиле? Юзер. 
Вся работа с ним, поэтому возвращай круд на юзера и читай рест.
у тебя ссылки должны соответствовать ресурсам, существующим, а не фиктивным. Поэтому работа с профилем у тебя должна быть минимальна, этого ресурса не существует, #show и всё
http://guides.rubyonrails.org/routing.html#singular-resources 
https://en.wikipedia.org/wiki/Representational_state_transfer#Resource_identification_in_requests

2017-12-05 12:42 UTC, OleksiyNosov commented on config/routes.rb
> +    resource :profile, only: %i[show create update]
то есть лучше написать так?

```sh
resources :users, only: %i[index create show update]
resource :profile, only: %i[show]
```

2017-12-11 07:55 UTC, kohigh requested changes

2017-12-11 07:55 UTC, donasktello commented on Gemfile
> +  gem 'pry-byebug'
добавь в дев, тест группу, пжлст.

2017-12-11 07:55 UTC, donasktello commented on config/routes.rb
> +    resources :users, only: %i[index show create show update]
сам найди, что не так =)

2017-12-11 07:55 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +    render status: 401 unless current_user
читай, чего не хватает твоей аутентификации
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2017-12-11 07:55 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +    token, _options = ActionController::HttpAuthentication::Token.token_and_options(request)
переменные с _ префиксом объявляют для приватного локального использования в методе. 
Ты с этой переменой вообще ничего не делаешь, поэтому

token, _ = ....
_ - условное обозначение конструкций в руби, которые не используются. Рубишный интерпретатор в данном случае возвращает последнее использованное значение, поэтому интерпретатор не тратит времени на выделение памяти для нового объекта.

2.4.1 :001 > a = [1, 2, 3]
 => [1, 2, 3] 
2.4.1 :002 > c, _ = a
 => [1, 2, 3] 
2.4.1 :003 > c
 => 1 
2.4.1 :004 > _
 => 1 
2.4.1 :005 >

2017-12-11 07:55 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +    @current_user = User.find decoded_token[0]['id'] if decoded_token
если токенизируешь айдишник, указывай, что это user_id, ты не только их можешь токенизировать для внутреннего общения в рамках твоего проекта.

2017-12-11 07:55 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +    nil
возвращай не nil, а false, для явного указания, что "пацан к успеху шёл, но не получилось, не срослось". Nil - это значение, для случаев, когда что-либо не найдено, а не ошибочно.

И объедини их в один блок через запятую, если у тебя одинаковая обработка.

2017-12-11 07:55 UTC, donasktello commented on app/serializers/session_serializer.rb
> +class SessionSerializer < ActiveModel::Serializer
Удаляй сериалайзер.
Сериалайзеры - промежуточная структура данных, между базой данных и последующим пользовательским **_выводом_**.
Пользователь о токене ничего не знает и не должен знать.
Предназначение сериалайзера вообще в том, что вот эта структура данных динамическая по своему предзначению. Структура данных может постоянно меняться, добавляться/удаляться атрибуты. У тебя же токен - это только токен, был, есть и будет.

2017-12-11 07:55 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +    JWT.decode token, Session::SECRET_KEY, true, algorithm: Session::ALGORITHM
это контрибутор аутентификации, а не внутренняя реализация.
Low cohesion - which is bad.

2017-12-11 07:55 UTC, donasktello commented on app/services/session.rb
> +    @token ||= JWT.encode payload, SECRET_KEY, ALGORITHM, headers
Декомпозируй отдельный сервис, который будет кодировать и декодировать токены.
Такой сервис у тебя должен быть универсальным, потому что предназначение токенов может быть не только для аутентификации. Но и для общения с микросервисами в рамках общей архитектуры, _например_.

2017-12-11 07:55 UTC, donasktello commented on app/services/session.rb
> +class Session
Класс сессии тоже не нужен. Мы от stateful аутентификации ушли для того, чтобы максимально сократить вообще данную схему.

Получил юзера, проверил пароль, выдал токен, не так много действий.
По идее( у меня так получилось) это займёт не так много места.

2017-12-11 07:55 UTC, donasktello commented on app/services/session_creator.rb
> +class SessionCreator < ResourceCrudWorker
Сервис тоже не нужен.
Во-первых он будет только в одном месте(Поэтому тут DRY не будет никогда).
Во-вторых его логика не будет расширяться и не будет.

2017-12-11 07:55 UTC, donasktello commented on db/migrate/20171205075219_add_index_to_email_in_users.rb
> +    add_index :users, :email, unique: true
убирай unique, это неверный подход

2017-12-11 15:47 UTC, kohigh requested changes

2017-12-11 15:47 UTC, donasktello commented on app/controllers/api/auth_tokens_controller.rb
> +  def user
у тебя класс нагружен 2 лишними методами, которые ты используешь в только в одном месте и которые, по факту, не упрощают твой класс, а загружают его лишними и строками, и вызовами)
find those methods.

2017-12-11 15:47 UTC, donasktello commented on app/controllers/api/auth_tokens_controller.rb
> +    JwtWorker.encode user_id: user.id, exp: 7.days.from_now.to_i
ты меня сильно буквально понял, наверное.
когда я сказал передавать exp, я же говорил, что, если тебе от JWT что-либо пригодится, так это токенизация и возможность передать exp. Поэтому надо предусмотреть интерфейс самого сервиса токенизации, чтобы можно было так делать.
В конкретно этой задаче передавать exp не надо(у тебя нет никаких требований к этому, но такие задачи могут быть, поэтому и нужно соблюсти возможность передачи exp), у тебя должно быть дефолтное какое=то значение, его и устанавливай.

2017-12-11 15:47 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +    render header: 'WWW-Authenticate', status: 401 unless current_user
не работает.

2017-12-11 15:47 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +    @decoded_token ||= JwtWorker.decode token
token у тебя промежуточная переменная, чтобы найти юзера. ты юзера нашёл, закешировал.
зачем тебе инстансная закешированная переменная токена?
удаляй метод, он не нужен.

2017-12-11 15:47 UTC, donasktello commented on app/services/jwt_worker.rb
> +  HEADERS = { typ: 'JWT', alg: ALGORITHM }.freeze
выведи в константы то, что тебе сейчас нужно для задачи.
ALGORITHM нужен для сигнатуры, SECRET_KEY тоже, ок. 
HEADERS удаляй.

private_constant :ALGORITHM, :HEADERS, :SECRET_KEY
.freeze
зачем?

у тебя итак объявлены константы, адекватные кодеры их не меняют.
случай неадекватных кодеров мы не рассматриваем, в таком случае поменянные константы будут меньшей из зол.
фриз вообще самый бестолковый метод. один хрен константу менять можно)

2017-12-12 14:55 UTC, kohigh requested changes

2017-12-12 14:55 UTC, donasktello commented on app/controllers/api/questions_controller.rb
>      params.require(:question).permit(:title, :body, tags: [])
найди лишнее.

2017-12-12 14:55 UTC, donasktello commented on app/controllers/api/auth_tokens_controller.rb
> +    params.require(:auth_token).permit(:email, :password)
у тебя хоть контроллер и для токена(т.к. у тебя сам роут на токены идёт), но сама форма с ключом токена и инпут полями email, password бессмысленна.
`params.require(:login)` что угодно в этом духе.

2017-12-12 14:55 UTC, donasktello commented on app/controllers/concerns/authenticatable.rb
> +      (@decoded_token = JwtWorker.decode token) && (@current_user = User.find @decoded_token.first['user_id'])
зачем инстансная переменная @decoded_token ?
current_user понятно, ты его повсеместно используешь из атр_ридера.

меняй на локальную

2017-12-12 14:55 UTC, donasktello commented on app/controllers/api/questions_controller.rb
>  class Api::QuestionsController < ApplicationController
в QuestionsController и AnswersController есть экшены, где sign_in не нужен и нужно бы эту возможность проверить.

2017-12-12 14:55 UTC, donasktello commented on spec/controllers/api/answers_controller_spec.rb
> +    before { sign_in }
даю лёгонькую подсказочку. у тебя там контекст повторяется по воркфлоу( аутентификация - > action ), можно было бы вынести before хук на один уровень в таких экшенах в целях DRY

2017-12-12 14:55 UTC, donasktello commented on spec/support/authetication.rb
> +    user ||= User.new
дыряво.

Во-первых это не похоже на логику дубля( мы же тут задублить хотели этим модулем ), если уже есть вариант использования реального объекта( особенно без явного указания этого )
Во-вторых, у тебя логика дубля должна повторять твой воркфлоу.
в твоём воркфлоу тебе для sign_in нужен юзер, а не опционально )
Особенно херово то, что он неявно устанавливается внутри.
т.е. я, как разработчик сторонний смотрю на сигнатуру(типа сваггера, не зная, как метод реализован), вижу, что юзера нужно передавать, ага, збс. Значит не передаю - и ошибка - а вот хуй там. 
 Ну и напоследок, можно было бы сократить  до `def sign_in user = User.new`
И, если бы ты бездумно не копировал чей-то код, а писал бы сам, я думаю сделал бы лучше =)

2017-12-12 14:55 UTC, donasktello commented on spec/support/authetication.rb
> +    allow(controller).to receive(:authenticate).and_return user
хоть authenticate и возвращает юзера, ты то этим не пользуешься, тебе достаточно убедиться, что вызов произошёл, значит, что это? =)

2017-12-13 10:00 UTC, donasktello commented on spec/requests/authentication_spec.rb
> +  let(:json_user) { { id: user.id, email: user.email }.to_h.stringify_keys }
wtf
`let(:json_user) { { 'id' => user.id, 'email' => user.email } }`, не?
П.С. ты, когда файл называешь, не называешь же его txt_sample или txt.sample
сначала идёт название, потом расширение. то же правило и относительно переменных работает, поменяй ;)

2017-12-13 10:06 UTC, donasktello commented on spec/requests/authentication_spec.rb
> +    it { expect(response).to have_http_status 401 }
не хватает проверки на хедер WWW-Authenticate

2017-12-13 10:18 UTC, donasktello commented on spec/services/jwt_worker_spec.rb
> +  let(:token) { JWT.encode payload, secret, algorithm }
весь тест неправильный.

у тебя для того и существует JwtWorker, что он адаптер(для сокрытия деталей реализации)
Ты поменяешь в будущем реализацию токенизатора на какой-то другой гем или вообще что-либо другое тебе придётся переписывать тест.
тесты лучше писать таким образом, чтобы их не приходилось переписывать( если есть такая возможность)

протестируй за раз и енкод и декод - передай данные на енкод и удостоверься, что декод вернёт их же.

что на случайную строку на декод он вернёт ошибку декодирования.

и что на просроченный токен вернёт ошибку.

3 теста.

2017-12-13 10:19 UTC, donasktello commented on app/services/jwt_worker.rb
> +class JwtWorker
поменяй название класса на JWTWorker. чтобы было понятно, что это аббревиатура в префиксе.

2017-12-13 10:20 UTC, donasktello commented on spec/models/user_spec.rb
> +  it { is_expected.not_to allow_value('test@test').for(:email) }
если хочешь проверить массив невалидных значений, достаточно объявить массив и в иче проверить каждое ;)

2017-12-13 11:37 UTC, OleksiyNosov commented on spec/controllers/application_controller_spec.rb
> +      #
но ведь это не закоментированый код, а коментари который говорит что означаэт данная ёлочка

2017-12-13 13:13 UTC, donasktello commented on spec/controllers/api/questions_controller_spec.rb
> +      before { allow(subject).to receive(:resource).and_raise ActiveRecord::RecordNotFound }
expect( и в других местах тоже меняй )
это поведение, а не состояние.

2017-12-13 13:18 UTC, donasktello commented on spec/controllers/concerns/authenticatable_spec.rb
> +  subject { ApplicationController.new }
ВО-первых ApplicationController "условно" абстрактный класс.
Во-вторых сейчас ты тест Authenticable привязал к обязательному наличию ApplicationController, хотя они не обязаны существовать в рамках одной системы.
`subject { Class.new }`
У нас модуль Authenticable должен быть плагином для любого класса, вот такой конструкцией ты это подчеркнёшь.

2017-12-13 13:21 UTC, donasktello commented on spec/models/user_spec.rb
> +  it { is_expected.not_to allow_values(invalid_mails).for(:email) }
плюс за грамотный подход.

2017-12-13 13:30 UTC, donasktello commented on spec/controllers/api/auth_tokens_controller_spec.rb
> +  let(:user) { FactoryBot.create(:user, email: 'test@example.com', password: 'user_password') }
зачем?
делай стаб

2017-12-13 16:04 UTC, donasktello commented on spec/services/jwt_worker_spec.rb
> +      it('returns decoded token') { expect(JWTWorker.decode token).to eq decoded_token }
Смотри в чём дыра.
Ты не передаёшь алгоритм шифрования, но ты проверяешь, что ты получаешь именно HS256.

Кейсы:
- Если ты поменяешь дефолтный алгоритм? Уже тест будет валиться, хотя воркфлоу по-прежнему будет работать.
- Если ты поменяешь токенизатор JWT на какой-либо? Так бы это осталось деталью внутренней реализации, на которую твой тест не опирается и, возможно, тест менять бы не пришлось, если бы ты проверял в ответе наличие только тех атрибутов, которые передал.

- Ну и самое херовое, что ты нагрузил тест лишней информацией, которая усложняет и чтение, и поддержку, а на работу самого класса никак не влияет. Тебе нужно проверить, что ты передал данные, и что они присутствуют в ответе. Всё, больше проверять не надо.

2017-12-14 09:32 UTC, donasktello commented on spec/controllers/concerns/resourceable_spec.rb
> +RSpec.describe Resourceable do
вот тест и показываеТ, что уровень твоей абстракции заставляет писать дичь в тестах, чтобы протестировать всё.
Фейковые объекты имеет смысл создавать, чтобы избежать нагрузки интерпретатора конструированием реальных объектов с их иерархией, кучей методов и тд. Ты же создаёшь фейковый класс, при этом загружаешь фулл стек обычного контроллера, не надо так, удаляй
+ У тебя тест сложнее самой логики и из теста нихуя не понятно, что и для чего тут делается, с точки зрения человека стороннего.

Как я предлагаю сделать и мне кажется это приемлемым в текущей ситуации.
Перепиши сам модуль и сделай `resource_creator`, `resource_updator` публичными, а остальные оставь приватными, чтобы разделить главные и вспомогательные методы.
Для примера возьми UsersController - он есть в любом проекте, а если нет, нет смысла делать проект на чём-то сложнее вордпресса.
Ну и заодно это будет показательно и понятно, чем просто FakesController.
Чем ближе пример к жизни, тем проще человеку будет читать твой тест, как документацию.
Протестируй вызовы `resource_creator`, `resource_updator` и всё
В качестве стаба у тебя будет User.find, он протестирует всю цепочку методов
`resource` `resource_class` `resource_class_name` и тебе не нужно будет их тестировать отдельно. Это вот как раз тот пример правила дублей "не тестируй внутреннюю логику", это внутренняя логика, которая каким-то образом вычисляет константу ресурса 
В качестве моков у тебя будет првоерка на то, что в итоге вызвались
`ResourceCreator.new` `ResourceUpdator.new`
ну и определяя UsersController, установи у него `resource_params`, чтобы проверить на моке вызов, что эти параметры передались.

2017-12-18 12:48 UTC, donasktello commented on spec/controllers/api/answers_controller_spec.rb
> +      before { allow(Answer).to receive(:new).with(permit! attributes).and_return answer }
у тебя на то сервис и есть, чтобы инкапсулировать всю логику тогО, как ты взаимодействуешь с ресурсом, поэтому, если ты саму логику инкапсулируешь, то и тесты у тебя должны быть такими же.
Т.е., если ты чего и стабаешь, то вызовы самого сервиса. Соответственно внутреннюю же логику самого сервиса ты можешь стабить только в его юнит тесте.

Т.к. в данной имплементации у тебя не получится переписать тесты, как мы хотим их видеть(тут без вариантов), чтобы архитектура осталась на своих местах, там, где используешь виспер и нужно проверить работу блока, т.е. контроллерами, работай с реальными объектами, без стабов. В самих же сервисах стабы оставь.

2017-12-18 12:58 UTC, donasktello commented on spec/controllers/api/questions_controller_spec.rb
> +      before { expect(subject).to receive(:collection).and_raise ActiveRecord::RecordNotFound }
лишнее

2017-12-18 13:04 UTC, donasktello commented on spec/rails_helper.rb
>    config.include Permitter
давай без неё, читаемость тестов усложняется.
P.S. если есть пермит, делать бенг метод алиас на обычный метод нельзя, потому что существует определённая конвенция, которая отличает обычный метод от бенгера.

2017-12-20 12:06 UTC, kohigh requested changes

2017-12-20 12:06 UTC, donasktello commented on app/controllers/application_controller.rb
> +
rescue_from ActionController::ParameterMissing и в юзерсконтроллер проверь

2017-12-20 12:06 UTC, donasktello commented on spec/controllers/api/answers_controller_spec.rb
> +      before { Answer.destroy_all }
добавь DatabaseCleaner, раз уж всё равно переписывать тесты

2017-12-26 14:08 UTC, kohigh requested changes

2017-12-26 14:08 UTC, donasktello commented on spec/rails_helper.rb
> +    (expected.length == actual.length) && (expected & actual == expected)
давай без объявления этих непонятных метчеров, в которых ещё нужно разбираться.

просто проверь, что в [0] есть нужные атрибуты, и, что в [1] есть нужные атрибуты, как ты проверяешь на джсоне, но вот в таком формате

2017-12-26 14:08 UTC, donasktello commented on spec/support/response_parser.rb
> +module ResponseParser
удаляй, не нужон он тебе.

2017-12-28 15:02 UTC, kohigh requested changes

2017-12-28 15:02 UTC, donasktello commented on spec/controllers/api/auth_tokens_controller_spec.rb
> +  let(:exp) { 7.days.from_now.to_i }
не усложняй лишней информацией тест.
тут этот эксп не нужен, он там по дефолту проставляется

2017-12-28 15:02 UTC, donasktello commented on spec/rails_helper.rb
> +require 'database_cleaner'
удаляй

2017-12-28 15:02 UTC, donasktello commented on spec/services/resource_crud_worker_spec.rb
> +    it('raise NotImplementedError') { expect { ResourceCrudWorker.new }.to raise_error NotImplementedError }
verifies that ResourceCrudWorker is an abstract class.

2017-12-29 12:29 UTC, Alexbaboshyn commented on spec/controllers/api/answers_controller_spec.rb
> +        before { expect(creator).to receive(:on).twice.and_call_original }
Мне кажется что эти два before хука можно реализовать с помощь елочки, так как мы в первом получаем creator и во втором вызываем на нем метод

2017-12-29 12:55 UTC, Alexbaboshyn commented on spec/controllers/api/answers_controller_spec.rb
> +        before { expect(creator).to receive(:on).twice.and_call_original }
Мне кажется что эти два before хука можно реализовать с помощь елочки, так как мы в первом получаем creator и во втором вызываем на нем метод

2017-12-29 12:55 UTC, Alexbaboshyn commented on spec/controllers/api/answers_controller_spec.rb
> +        before { expect(updator).to receive(:on).twice.and_call_original }
Елка

2017-12-29 12:55 UTC, Alexbaboshyn commented on spec/controllers/api/answers_controller_spec.rb
> +        before { expect(creator).to receive(:on).twice.and_call_original }
Елка

2017-12-29 12:55 UTC, Alexbaboshyn commented on spec/controllers/api/answers_controller_spec.rb
> +        before { expect(updator).to receive(:on).twice.and_call_original }
Елка

2017-12-29 12:55 UTC, Alexbaboshyn commented on spec/controllers/api/answers_controller_spec.rb
> +        before { expect(destroyer).to receive(:on).twice.and_call_original }
Елка

2017-12-29 12:55 UTC, Alexbaboshyn commented on spec/controllers/api/auth_tokens_controller_spec.rb
> +      before { allow(user).to receive(:authenticate).and_return true }
Елка. Ну и так же в других контроллерах

2017-12-29 12:55 UTC, Alexbaboshyn commented on spec/controllers/api/answers_controller_spec.rb
> +        before { expect(destroyer).to receive(:on).twice.and_call_original }
Елка

2017-12-29 16:55 UTC, kohigh approved these changes

2017-12-29 16:59 UTC, merged